package com.shop.entities;
// default package
// Generated Jun 29, 2017 8:24:48 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {

	private static final long serialVersionUID = 3494725537790558992L;
	
	@ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
  private Order order;
  
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
  private Product product;

	public OrderDetailId() { }
  public OrderDetailId(Order order, Product product) {
    super();
    this.order = order;
    this.product = product;
  }


  public Order getOrder() {
    return order;
  }

  public void setOrder(Order order) {
    this.order = order;
  }

  public Product getProduct() {
    return product;
  }

  public void setProduct(Product product) {
    this.product = product;
  }
	
}
