package com.shop.entities;
// default package
// Generated Jun 29, 2017 8:24:48 PM by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "`order`")
public class Order {

	public static final short new_od = 1;
	public static final short paid = 2;
	public static final short delivery = 3;
	public static final short success = 10;
	public static final short canceled = -1;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	private String customerName;
	private String phoneNumber;
	private String address;
	private Double total;
	
  @Column(name = "date", nullable = false)
	private Date created;
	private Short status;
	private String payment;
	
	public String getPayment() {
    return payment;
  }

  public void setPayment(String payment) {
    this.payment = payment;
  }

	public Order() {
	}

	public Order(String customerName, String phoneNumber, String address, Double total, Date created, Short status) {
		this.customerName = customerName;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.total = total;
		this.created = created;
		this.status = status;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "customer_name", nullable = false, length = 50)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "phone_number", nullable = false, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "total", nullable = false)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false)
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

  @Override
  public String toString() {
    return "Order [id=" + id + ", customerName=" + customerName + ", phoneNumber=" + phoneNumber
        + ", address=" + address + ", total=" + total + ", created=" + created + ", status="
        + status + ", payment=" + payment + "]";
  }
}
