package com.shop.entities;
// default package
// Generated Jun 29, 2017 8:24:48 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;

import org.hibernate.validator.constraints.Length;
import org.springframework.web.multipart.MultipartFile;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = 129666795222060860L;
	
	@Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", unique = true)
	private Long id;
	
	@OneToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "cate_id", nullable = false, insertable = true)
	private Category category;
	@NotBlank(message = "Tên sản phẩm không được để trống")
	@Length(max = 50, message = "Tên sản phẩm không được quá 50 ký tự .")
	private String name;
	private long price;
	private int quantity;
	private String image;
	private int views;
	
	@OneToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "brand_id", nullable = true, insertable = true)
  private Brand brand;
	
	
	public Brand getBrand() {
    return brand;
  }

  public void setBrand(Brand brand) {
    this.brand = brand;
  }
  @NotBlank(message = "Ngày nhập không được để trống")
  private String date;
	
	public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  @Transient
	private MultipartFile file_image;
	

  public MultipartFile getFile_image() {
    return file_image;
  }

  public void setFile_image(MultipartFile file_image) {
    this.file_image = file_image;
  }

  @Column(columnDefinition = "TEXT")
	private String description;
	
	@Transient
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);
	
	@Transient
	private Set<OrderDetail> orderDetails_1 = new HashSet<OrderDetail>(0);

	public Product() {
	}

	
	public Product(Long id, Category category, String name, long price, int quantity, String image,
                 int views, Brand brand, String date, MultipartFile file_image, String description,
                 Set<OrderDetail> orderDetails, Set<OrderDetail> orderDetails_1) {
    super();
    this.id = id;
    this.category = category;
    this.name = name;
    this.price = price;
    this.quantity = quantity;
    this.image = image;
    this.views = views;
    this.brand = brand;
    this.date = date;
    this.file_image = file_image;
    this.description = description;
    this.orderDetails = orderDetails;
    this.orderDetails_1 = orderDetails_1;
  }

  public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false)
	@Min(value = 1, message = "Giá không được nhỏ hơn 1 .")
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}
	@Min(value = 1, message = "Số lượng không được nhỏ hơn 1 .")
	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "views", nullable = false)
	public int getViews() {
		return this.views;
	}

	public void setViews(int views) {
		this.views = views;
	}

	@Column(name = "description", nullable = false)
	@NotBlank(message = "Mô tả không được để trống")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderDetail> getOrderDetails_1() {
		return this.orderDetails_1;
	}

	public void setOrderDetails_1(Set<OrderDetail> orderDetails_1) {
		this.orderDetails_1 = orderDetails_1;
	}

  @Override
  public String toString() {
    return "Product [id=" + id + ", category=" + category + ", name=" + name + ", price=" + price
        + ", quantity=" + quantity + ", image=" + image + ", views=" + views + ", brand=" + brand
        + ", date=" + date + ", file_image=" + file_image + ", description=" + description + "]";
  }
}
