package com.shop.entities;
// default package
// Generated Jun 29, 2017 8:24:48 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import com.querydsl.core.support.QueryMixin.Role;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "user")
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 3652701442993010762L;
	
	@Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
	private Long id;
	private String name;
	private String username;
	private String password;
	private String address;
	private String phone;
	private String email;
	private Integer role;
	

	public Users() { }
  public Users(Long id, String name, String username, String password, String address,
              String phone, String email, Integer role) {
    super();
    this.id = id;
    this.name = name;
    this.username = username;
    this.password = password;
    this.address = address;
    this.phone = phone;
    this.email = email;
    this.role = role;
  }


  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Integer getRole() {
    return role;
  }

  public void setRole(Integer role) {
    this.role = role;
  }

}
